/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package openingGUI;

import pkg2dgame.Game;

/**
 *
 * @author Joseph
 */
public class AISettingsGUI extends javax.swing.JFrame {

    /**
     * Creates new form AISettingsGUI
     */
    public AISettingsGUI() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        speedLabel = new javax.swing.JLabel();
        tempermentLabel = new javax.swing.JLabel();
        acceptButton = new javax.swing.JButton();
        speedCombo = new javax.swing.JComboBox();
        tempermentCombo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLabel.setText("AI SETTINGS");

        speedLabel.setText("PLAY SPEED");
        speedLabel.setToolTipText("Slow to improve performance");

        tempermentLabel.setText("TEMPERMENT");
        tempermentLabel.setToolTipText("How aggressive the AI is");

        acceptButton.setText("ACCEPT");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        speedCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Very Slow", "Slow", "Standard", "Fast" }));
        speedCombo.setSelectedIndex(2);
        speedCombo.setSelectedItem(this.speedCombo.getItemAt(2));
        speedCombo.setToolTipText("");
        speedCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speedComboActionPerformed(evt);
            }
        });

        tempermentCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Very Aggressive", "Aggressive", "Standard", "Careful" }));
        tempermentCombo.setSelectedIndex(2);
        tempermentCombo.setSelectedItem(this.speedCombo.getItemAt(2));
        tempermentCombo.setToolTipText("");
        tempermentCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempermentComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(speedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tempermentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acceptButton)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tempermentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(speedCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speedCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempermentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempermentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(acceptButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        switch(this.speedCombo.getSelectedIndex()){
            case 0: //very slow
                Game.enemyAI.playSpeed = 300;
                System.out.println("AI speed set to 300");
                break;
            case 1: //slow
                Game.enemyAI.playSpeed = 200;
                System.out.println("AI speed set to 200");
                break;
            case 2: //standard
                Game.enemyAI.playSpeed = 100;
                System.out.println("AI speed set to 100");
                break;
            case 3: //fast
                Game.enemyAI.playSpeed = 60;
                System.out.println("AI speed set to 60");
                break;
            default: System.out.println("AI Settings: Unknown speed index " + this.speedCombo.getSelectedIndex());
                break;
        }
        
        switch(this.tempermentCombo.getSelectedIndex()){
            case 0: //Very Aggressive
                Game.enemyAI.timidness = -3;
                break;
            case 1: //Aggressive
                Game.enemyAI.timidness = 0;
                break;
            case 2: //Standard
                Game.enemyAI.timidness = 3;
                break;
            case 3:
                Game.enemyAI.timidness = 6;
                break;
            default: System.out.println("AI Settings: Unknown temperment index " + this.tempermentCombo.getSelectedIndex());
                break;
        }
        this.dispose();
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void speedComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speedComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_speedComboActionPerformed

    private void tempermentComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempermentComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempermentComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        AISettingsGUI asg = new AISettingsGUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JComboBox speedCombo;
    private javax.swing.JLabel speedLabel;
    private javax.swing.JComboBox tempermentCombo;
    private javax.swing.JLabel tempermentLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
